config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'landing_page#index'

  get    'search_page'                  => 'landing_page#search_page'
  get    'verification_status'          => 'landing_page#verification_status'
  post   'contact_create'               => 'landing_page#contact_create'

  get    'login'                        => 'sessions#new'
  get    'signup'                       => 'users#new'
  get    'login'                        => 'sessions#new'
  post   'login'                        => 'sessions#create'
  delete 'logout'                       => 'sessions#destroy'
  

  get    'apply'                        => 'student_verification#apply'
  post   'apply'                        => 'student_verification#apply'
  get    'status'                       => 'student_verification#status'

  get    'history'                      => 'student_verification#history'
  post   'proceed_to_pay'               => 'student_verification#proceed_to_pay'
  get    'payment_confirmation'         => 'student_verification#payment_confirmation'
  post   'instamojo_webhook'            => 'student_verification#instamojo_webhook'
  post   'add_verification'             => 'student_verification#add_verification'
  get    'final_report_user'            => 'student_verification#report'
  get    'payment_report'               => 'student_verification#payment_report'

  get    'view_verifications'           => 'college_verification#index'
  get    'completed_verifications'      => 'college_verification#completed'
  get    'payment_details'              => 'college_verification#payment'
  put    'update'                       => 'college_verification#update'
  get    'final_report'                 => 'college_verification#report'
  get    'college_payment_report'       => 'college_verification#payment_report'

  

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :users, except: [:show]
  resources :colleges
  resources :report_data, only: [:index, :update]

get 'application/raise_not_found'
get '*a' => redirect("application/raise_not_found")

end

app/controllers/student_verification_controller.rb
class StudentVerificationController < ApplicationController
	include StudentVerificationHelper
	helper_method :sort_column, :sort_direction

	before_action :logged_in_user, only: [:apply, :status, :history, :report, :payment_report]
	before_action :set_s3_direct_post, only: [:apply]
	skip_before_filter :verify_authenticity_token, :except => [:add_verification, :instamojo_webhook]

	require 'httparty'
	
	def apply
        if request.post?
        	puts "post request"
			redirect_to payment_path
		else
			@colleges = College.all
			if(params.has_key?(:college_id))
	        	@college_id = params[:college_id]
	        end
	        @college = College.first 
	        render 'apply'
		end
	end

	def add_verification
		@verification_request = VerificationRequest.new(verification_params)
		@college_ver = College.where(:id => @verification_request.college_id).first
		@verification_request.amount = @college_ver.verification_amount
		@verification_request.verification_status_id = 1
		@verification_request.service_tax = ENV['DEFAULT_VERF_AMOUNT'].to_f * (1 + ENV['TAX_PERCENT'].to_f / 100)

	    # respond_to do |format|
	      if @verification_request.save
	        # format.html { redirect_to @verification_request, notice: 'Student was successfully created.' }
	        url = HTTParty.get("#{ENV['MVAAYOO_URL']}?user=#{ENV['MVAAYOO_USER']}:#{ENV['MVAAYOO_PASSWORD']}&senderID=TEST%20SMS&receipientno=#{@college_ver.user.phone}&msgtxt=New verification for #{@college_ver.name}. Name: #{@verification_request.name}. Hallticket: #{@verification_request.hallticket_no}&state=4")
	        render json: @verification_request.to_json
	        # Mvaayoo.send_message "New verification for #{@college_ver.name}. Name: #{@verification_request.name}. Hallticket: #{@verification_request.hallticket_no}", @college_ver.user.phone
	        # format.json { render :show, status: :created, location: @verification_request }
	      else
	        # format.html { render :new }
	        # format.json { render json: @verification_request.errors, status: :unprocessable_entity }
	        render json: @verification_request.errors
	      end
	    # end
	end

	def report
	    @disable_header_footer = true
	    @verification_stub = VerificationRequest.find_by(id: params[:verification_id])
	    @college = College.find(@verification_stub.college_id)
	    @user = User.find_by(id: @verification_stub.user_id)
	    # @client_ip = request.remote_ip
	    respond_to do |format|
	      format.pdf do
	        pdf = WickedPdf.new.pdf_from_string(
	          render_to_string(template: "report_data/report.html.erb"),
	          :footer => {right: "Powered by www.verifyonline.in"}
	        ) 
	        send_data(pdf, 
	          :filename    => "report_#{@verification_stub.name.gsub(/\s+/, "")}_#{@verification_stub.hallticket_no}.pdf", 
	          :disposition => 'attachment'
	        )
	      end
	    end
	end

	def payment_report
		@disable_header_footer = true
		@student_verifications =  VerificationRequest.select("payment_id").where("user_id = ?", current_user.id)
	    @searched = false
		if params.has_key?(:fromdate) && params.has_key?(:todate)
	      @fromDate = Date.parse(params[:fromdate]) rescue nil
	      @toDate = Date.parse(params[:todate]) rescue nil
	      if @fromDate.present? && @toDate.present?
		      @payments = Payment.all.where(:id => @student_verifications).where(
		        "date(created_at) BETWEEN ? AND ?", 
		        "%#{params[:fromdate]}%",
		        "%#{params[:todate]}%"
		        ).order('created_at ASC')
		      @searched = true
		  end 
	    end
	    respond_to do |format|
	      format.pdf do
	        pdf = WickedPdf.new.pdf_from_string(
	          render_to_string(template: "report_data/payment_report.html.erb"),
	          :footer => {right: "Powered by www.verifyonline.in", left: 'Page [page] of [topage]' }
	        ) 
	        send_data(pdf, 
	          :filename    => "payment_report.pdf", 
	          :disposition => 'attachment'
	        )

	        # render  pdf: "report_#{@verification_stub.name.gsub(/\s+/, "")}_#{@verification_stub.hallticket_no}", 
	        #         template: "college_verification/report.html.erb"
	      end
	    end
	end

	def status
		if params.has_key?(:search_tag)
	      @verifications =  VerificationRequest.all.where(
	        " payment_id IS NOT null AND user_id = ? AND (hallticket_no ILIKE ? OR name ILIKE ? OR verification_token ILIKE ?)", 
	          current_user.id, 
	          "%#{params[:search_tag]}%",
	          "%#{params[:search_tag]}%",
	          "%#{params[:search_tag]}%"
	        ).order('created_at DESC')
	      .paginate(page: params[:page],:per_page => 10)
	    else  
	      @verifications =  VerificationRequest.all.where(
	        "payment_id IS NOT null AND user_id = ?", 
	          current_user.id
	        ).order('created_at DESC')
	      .paginate(page: params[:page],:per_page => 10)
	    end
	end

	def history
		@college_verifications =  VerificationRequest.select("payment_id").where("user_id = ?", current_user.id)
	    @searched = false
	    if params.has_key?(:search_tag)
	      @payments = Payment.all.where(:id => @college_verifications).where(
	        "transaction_id ILIKE ?", 
	        "%#{params[:search_tag]}%",
	        ).order('created_at DESC')
	      .paginate(page: params[:page],:per_page => 10)
	      @searched = true
	    elsif params.has_key?(:fromdate) && params.has_key?(:todate)
	      @fromDate = Date.parse(params[:fromdate]) rescue nil
	      @toDate = Date.parse(params[:todate]) rescue nil
	      if @fromDate.present? && @toDate.present?
		      @payments = Payment.all.where(:id => @college_verifications).where(
		        "date(created_at) BETWEEN ? AND ?", 
		        "%#{params[:fromdate]}%",
		        "%#{params[:todate]}%"
		        ).order('created_at DESC')
		      .paginate(page: params[:page],:per_page => 10)
		      @searched = true
		  end 
	    end
	end

	def proceed_to_pay
		if(params.has_key?(:verification_ids))
			verification_ids = params["verification_ids"].split(",")
			@ver_data = VerificationRequest.all.where("id = ?", verification_ids[0]).first
			puts "Ver DATA"
			puts @ver_data.inspect
			# puts @ver_data.to_yaml

			@user = User.where("id = ?", @ver_data.user_id).first
			amount = 0
			verification_ids.map do |e|
	            ver = VerificationRequest.all.where("id = ?", e).first
	            amount += ver.amount + (ENV['DEFAULT_VERF_AMOUNT'].to_f * (1 + ENV['TAX_PERCENT'].to_f / 100))
	        end
	        amount = amount.ceil
	        puts amount
	        puts "Amount sent is ^"

			@result = HTTParty.post("https://www.instamojo.com/api/1.1/links/", 
			    :body => { 
			    	:title => "Verify Online", 
	                :description => "Hi #{@user.name}, \nProceed with payment above to complete your verification process.\n\nPlease contact support@verifyonline.in for any queries.", 
	                :currency => 'INR',
            		:quantity => 1,
            		# :buyer_name => "#{@user.name}",
            		# :email => "#{@user.email}",
            		# :phone => "#{@user.phone}",
            		# :allow_repeated_payments => false,
	                :base_price => "#{amount}", 
	                :redirect_url => "#{request.base_url}/payment_confirmation",
	                :webhook_url => "#{request.base_url}/instamojo_webhook"
	                # :webhook_url => "http://requestb.in/16bls4y1"
			    },
			    :headers => { 
			    	'X-Api-Key' => "#{ENV['INSTAMOJO_API_KEY']}",
					'X-Auth-Token' => "#{ENV['INSTAMOJO_AUTH_TOKEN']}"
				} 
			)
			puts @result.inspect
			VerificationRequest.where("id" => verification_ids).update_all(payment_slug: @result.parsed_response["link"]["slug"])
			# redirect_to @result.parsed_response["link"]["url"]
			data = JSON.parse("{\"url\":\"#{@result.parsed_response["link"]["url"]}?embed=form\"}")
			render json: data
		end
	end

	def payment_confirmation 
		@payment_id = params['payment_id']
	end

	def instamojo_webhook
	    params_data = instamojo_webhook_params
	    params_data[:transaction_id] = params_data.delete :payment_id

	    @payment = Payment.new(params_data)
		@payment.save
		VerificationRequest.where("payment_slug" => params["offer_slug"]).update_all(payment_id: @payment.id)
	end

	private

		def verification_params
	     	params.require(:verification_request).permit(:user_id, :college_id, :name, :hallticket_no, :document_link)
	    end

	    def instamojo_webhook_params
	    	# params.permit(:variants, :buyer, :custom_fields, :buyer_name, :amount, :mac, :offer_title, :fees, :offer_slug, :buyer_phone, :payment_id, :quantity, :currency, :status, :unit_price)
	    	params.permit(:payment_id, :buyer, :buyer_name, :amount, :mac, :offer_title, :fees, :buyer_phone, :currency, :status)
	    end

		def set_s3_direct_post
			@s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
		end


  
		def sort_column
			VerificationRequest.column_names.include?(params[:sort]) ? params[:sort] : "name"
		end

		def sort_direction
			%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
		end

end

app/helpers/student_verification_helper.rb
module StudentVerificationHelper

	def verifyChecksum( merchantID,  orderID,  amount,  authDesc,  workingKey,  checksum) 

		String str = merchantID+“|”+orderID+“|”+amount+“|”+authDesc+“|”+workingKey

		String newChecksum = Zlib::adler32(str).to_s

		return (newChecksum.eql?(checksum)) ? true : false

	end

	def getChecksum( merchantID,  orderID,  amount,  redirectUrl,  workingKey) 

		String str = merchantID + “|” + orderID + “|” + amount + “|” + redirectUrl + “|” + workingKey;

		return Zlib::adler32(str)

	end

	def encrypt_string(ccaRequest)
		Dir.chdir("#{RAILS_ROOT}/public/jars/") do

	      encRequest = %x[java -jar ccavutil.jar #{CCAVENUE_WORKING_KEY} "#{ccaRequest}" enc]

	    end
	    return encRequest
	end
	
	def decrypt_string(encRequest)
		Dir.chdir("#{RAILS_ROOT}/public/jars/") do

       		ccaResponse = %x[java -jar ravi-ccavutil.jar #{CCAVENUE_WORKING_KEY} "#{encResponse}" dec]

		end
	    return ccaResponse
	end


	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end


end

app/views/student_verification/_header.html.erb
  <style>
  	.tab_style{
  		background: #fff !important;
  		color: #111 !important;
  		border-color: transparent !important;
  	}
  </style>
  <%tab_style="tab_style"%>
  <!-- Page Loader -->        
  <div id="ptp_loader" class="page-loader" style="display:none;">
    <div class="loader">Loading...</div>
    <div style="width:300px; height: 50px; position: absolute; top: 65%; left: 50%; margin: -25px 0 0 -150px; font-size: 15px;">
    <p id="loader_msg" style="text-align: center;">AAA</p>
    </div>
  </div>
  <!-- End Page Loader -->

    <!-- Home Section -->
    <section class="home-section bg-dark-alfa-50 " style='background-color: #040F16;' id="home">
       <div class="container">            
            <!-- Hero Content -->
            <div class="home-content">
                <div class="home-text" style="padding: 45px 0px;">
                    
                    <!-- <h1 class="hs-line-8 no-transp font-alt mb-50 mb-xs-30">
                       Verification
                    </h1> -->                    
                    <div class="local-scroll hidden-xs">
                       <%= link_to "Apply", apply_path, :class => "btn btn-mod btn-border-w btn-medium btn-round #{tab_style unless params[:action]!='apply'}" %>
                        <span>&nbsp;</span>
                        <%= link_to "Status", status_path, :class => "btn btn-mod btn-border-w btn-medium btn-round #{tab_style unless params[:action]!='status'}" %>
                        <span>&nbsp;</span>
                        <%= link_to "Payment History", history_path, :class => "btn btn-mod btn-border-w btn-medium btn-round #{tab_style unless params[:action]!='history'}" %>
                    </div>                    
                </div>
            </div>
            <!-- End Hero Content -->            
       </div>
    </section>
    <!-- End Home Section -->

app/views/student_verification/history.html.erb
<div class="page" id="top">            
    <%= render 'student_verification/header'%> 
    
    <!-- Section -->
    <section class="small-section" id="multi-page">
        <div class="container relative">            
            <!--<h2 class="section-title font-alt mb-60 mb-sm-30">
                Multi Page Demo
            </h2> -->            
            <div class="row">                
                <!--<%= form_tag(:history, :method => "get", :html => { :class => 'form contact-form', :id => 'contact_form'}) do %>
                    <div class="clearfix">                                                  
                        <div class="form-group row">
                            <div class="col-md-6">
                                <input type="text" name="search_tag" id="search_tag" class="input-md round form-control" placeholder="Search by Transaction ID">
                            </div>
                            <div class="col-md-2">
                                <%= submit_tag "Search", :class => "submit_btn btn btn-mod btn-medium btn-round"%>
                            </div> 
                        </div>
                    </div>
                <% end %>
                <hr>-->
                <%= form_tag(:history, :method => "get", :html => { :class => 'form contact-form', :id => 'payment_form'}) do %>
                    <div class="clearfix">                                                  
                        <div class="form-group row">
                            <div class="col-md-2" style="font-size: 16px; color: #4C4A47; margin-top: 6px;">Search date range</div>
                            <div class="col-md-4">
                                <div class="input-group input-daterange">
                                    <input name="fromdate" id="fromdate" type="text" class="form-control" value=<%=@searched==true ? @fromDate: ""%>>
                                    <span class="input-group-addon">to</span>
                                    <input name="todate" id="todate" type="text" class="form-control" value=<%=@searched==true ? @toDate: ""%>>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <%= submit_tag "Search", :class => "submit_btn btn btn-mod btn-medium btn-round"%>
                            </div> 
                            <% if @payments.present? %>    
                            <div class="col-md-4">
                                <a href="/payment_report.pdf?fromdate=<%=@fromDate%>&todate=<%=@toDate%>" target="blank" style="cursor: pointer; font-size: 22px;"><i class="fa fa-download dark" style="padding: 5px 10px;"></i>Download Report</a>
                            </div> 
                            <%end%>
                        </div>
                    </div>
                <% end %> 

                <div class="mb-40 table-responsive " style="margin-top: 20px;">

                    <% if !@payments.present? %>    
                        <% if @searched == true %>    
                            <div class="jumbotron align-center">
                                <p>No payments match search criteria.</p>
                            </div>
                        <%else%>
                            <div class="jumbotron align-center">
                                <p>No payments have been made yet. Please <%= link_to "apply", apply_path%> for document verification.</p>
                            </div>
                        <%end%>
                    
                    <%else%>
                        <table class="table table-striped ">
                            <thead style="background: dimgrey; color: white;">
                              <tr>
                                <th>Sl. no.</th>
                                <th>Verification ID</th>
                                <th>Transaction ID</th>
                                <th>College/ University Name</th>
                                <th>Student Name</th>
                                <th>HT Number/ Reg. No.</th>
                                <th>Transaction Date and Time</th>
                                <th>Amount Paid</th>
                                <!-- <th>Paid on</th> -->
                              </tr>
                            </thead>
                            <tbody>
                            <% @payments.each_with_index do |payment, i| %>
                                <%
                                    @verification_stub = VerificationRequest.find_by(payment_id: payment.id)
                                    @college = College.find_by(id: @verification_stub.college_id)
                                %>
                              <tr>
                                <td><%=i+1%></td>
                                <td style="text-transform: uppercase;"><%=@verification_stub.verification_token%></td>
                                <td style="text-transform: uppercase;"><%=payment.transaction_id%></td>
                                <td><%=@college.name%></td>
                                <td><%=@verification_stub.name%></td>
                                <td style="text-transform: uppercase;"><%=@verification_stub.hallticket_no%></td>
                                <td><%=local_time(payment.created_at + 330.minutes, '%d/%m/%Y %l:%M%p')%></td>
                                <td>Rs <%=(@college.verification_amount + 114.5).round%></td>
                                <!-- <td><%=local_time(payment.created_at + 330.minutes, '%d/%m/%Y')%></td> -->
                              </tr>
                              
                            <% end %>
                        </table>
                        <%= will_paginate @payments %>
                    <%end%>

                </div>
            </div>       
        </div>
    </section>
    <!-- End Section -->
</div>

app/views/student_verification/payment_confirmation.html.erb
<div class="page" id="top">            
    <%= render 'student_verification/header'%>
    <!-- Section -->
    <section class="small-section" id="multi-page">
        <div class="container relative">            
            <!--<h2 class="section-title font-alt mb-60 mb-sm-30">
                Multi Page Demo
            </h2> -->            
            <div class="row">                
                <div class="mb-40 table-responsive ">   
                    <div class="jumbotron align-center">
                        <p>Payment Successful. Your transaction ID is <strong><%=@payment_id%></strong>. Click <%= link_to "here", apply_path%> to verify more documents. Keep this transaction ID for future references.</p>
                    </div>
                </div>
            </div>       
        </div>
    </section>
    <!-- End Section -->
</div>

app/views/student_verification/status.html.erb
<div class="page" id="top">            
    <%= render 'student_verification/header'%> 

    <!-- Section -->
    <section class="small-section" id="multi-page">
        <div class="container relative">            
            <!--<h2 class="section-title font-alt mb-60 mb-sm-30">
                Multi Page Demo
            </h2> -->            
            <div class="row">
                <div class="mb-40 table-responsive ">
                    <%= form_tag(:status, :method => "get", :html => { :class => 'form contact-form', :id => 'contact_form'}) do %>
                        <div class="clearfix">                                                  
                            <div class="form-group row">
                                <div class="col-md-5">
                                    <input type="text" name="search_tag" id="search_tag" class="input-md round form-control" placeholder="Search by name or hallticket number">
                                </div>
                                <div class="col-md-2">
                                    <%= submit_tag "Search", :class => "submit_btn btn btn-mod btn-medium btn-round"%>
                                </div> 
                            </div>
                        </div>
                    <% end %> 
                    <% if @verifications.blank? %>    
                        <div class="jumbotron align-center">
                            <p>You have no documents submitted yet. Please <%= link_to "apply", apply_path%> for document verification  </p>
                        </div>
                    
                    
                    <%else%>
                        <table class="table table-striped ">
                            <thead style="background: dimgrey; color: white;">
                              <tr>
                                <th>S.No.</th>
                                <th>Verification ID</th>
                                <th><%= sortable "name", "Name" %></th>
                                <th><%= sortable "hallticket_no", "HT Number/ Roll.No." %></th>
                                <th>College</th>
                                <th>Document</th>
                                <!-- <th><%= sortable "amount", "Amount" %></th> -->
                                <!-- <th>Service Tax</th> -->
                                <th>Request Date</th>
                                <th>Status</th>
                                <th>Report Date</th>
                                <th>Report</th>
                              </tr>
                            </thead>
                            <tbody>
                            <% @verifications.each_with_index do |verification, i| %>
                                <tr>
                                    <td><%=i+1%></td>
                                    <td style="text-transform: uppercase;"><%=verification.verification_token%></td>
                                    <td><%=verification.name%></td>
                                    <td style="text-transform: uppercase;"><%=verification.hallticket_no%></td>
                                    <td><%=verification.college.name%></td>
                                    <td><a href="<%=verification.document_link%> " target="blank"><i class="fa fa-download dark"></i></a>       </td>
                                    <!-- <td><%=verification.amount%></td> -->
                                    <!-- <td><%=verification.service_tax.round(2)%></td> -->
                                    <td><%=local_time(verification.created_at + 330.minutes, '%d/%m/%Y %l:%M%p')%></td>
                                    <td><%=verification.verification_status.description%></td>
                                    <%if verification.verification_status_id != 1%>

                                        <td><%=local_time(verification.updated_at + 330.minutes, '%d/%m/%Y %l:%M%p')%></td>
                                        <td>
                                            <a href="/final_report_user.pdf?verification_id=<%=verification.id%>" target="blank"><i class="fa fa-download dark"></i>&nbsp;</a>
                                        </td>
                                    <%else%>
                                        <td></td>
                                        <td></td>
                                    <%end%>
                                </tr>
                            <% end %>
                            </tbody>
                        </table>
                        <%= will_paginate @verifications %>

                    <%end%>

                </div> 
            </div>            
        </div>
    </section>
    <!-- End Section -->
</div>