config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'landing_page#index'

  get    'search_page'                  => 'landing_page#search_page'
  get    'verification_status'          => 'landing_page#verification_status'
  post   'contact_create'               => 'landing_page#contact_create'

  get    'login'                        => 'sessions#new'
  get    'signup'                       => 'users#new'
  get    'login'                        => 'sessions#new'
  post   'login'                        => 'sessions#create'
  delete 'logout'                       => 'sessions#destroy'
  

  get    'apply'                        => 'student_verification#apply'
  post   'apply'                        => 'student_verification#apply'
  get    'status'                       => 'student_verification#status'

  get    'history'                      => 'student_verification#history'
  post   'proceed_to_pay'               => 'student_verification#proceed_to_pay'
  get    'payment_confirmation'         => 'student_verification#payment_confirmation'
  post   'instamojo_webhook'            => 'student_verification#instamojo_webhook'
  post   'add_verification'             => 'student_verification#add_verification'
  get    'final_report_user'            => 'student_verification#report'
  get    'payment_report'               => 'student_verification#payment_report'

  get    'view_verifications'           => 'college_verification#index'
  get    'completed_verifications'      => 'college_verification#completed'
  get    'payment_details'              => 'college_verification#payment'
  put    'update'                       => 'college_verification#update'
  get    'final_report'                 => 'college_verification#report'
  get    'college_payment_report'       => 'college_verification#payment_report'

  

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :users, except: [:show]
  resources :colleges
  resources :report_data, only: [:index, :update]

get 'application/raise_not_found'
get '*a' => redirect("application/raise_not_found")

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-section footer" style="padding: 15px; background-color: #02121c;">
    <div class="container">
        
        <!-- Footer Logo -->
        <!-- <div class="local-scroll mb-30 wow fadeInUp" data-wow-duration="1.2s">
            <a href="#top"><img src=<%= image_path("logo-footer-new.png")%> width="78" height="36" alt="" /></a>
        </div>
 -->        <!-- End Footer Logo -->     

        
        <!-- Footer Text -->
        <div class="footer-text">
            
            <!-- Copyright -->
            <div class="footer-copy font-alt">
                <a href="http://www.verifyonline.in" target="_blank">&copy; Verify Online 2017</a>.
            </div>
            <!-- End Copyright -->
            
            <!-- <div class="footer-made">
                Made with love.
            </div> -->
            
        </div>
        <!-- End Footer Text --> 
        <% if params[:controller] =='landing_page' && params[:action] == 'index' %>
        <!-- Top Link -->
         <div class="local-scroll">
             <a href="#top" class="link-to-top"><i class="fa fa-caret-up"></i></a>
         </div>
         <!-- End Top Link -->
         <% end %>
        
     </div>
    
</footer>
<!-- End Footer -->

app/views/layouts/_header.html.erb
<!-- Navigation panel -->
<nav class="main-nav stick-fixed">

    <div class="full-wrapper relative clearfix">
        <!-- Logo ( * your text or image into link tag *) -->
        <div class="nav-logo-wrap local-scroll"> 
                <%= link_to image_tag("logo-white-new.png", alt: "Verify online logo", style: "padding: 9px;"), root_url, method: :get, class: "logo" %>
        </div>

           
      
        <div class="mobile-nav">     
        
            <i class="fa fa-bars"></i>
        </div>
        <!-- Main Menu -->
        <div class="inner-nav desktop-nav">
            <ul class="clearlist scroll-nav local-scroll">

                <% if params[:controller] =='landing_page' && params[:action] == 'index' %>
                    <li><a href="#home" class="active">Home</a></li>
                <% else %> 
                    <li><%= link_to "Home", root_url,method: :get %></li>
                <% end %>

                

                <% if logged_in? %>                  
                    <% if is_college_admin?  %>
                        <% if params[:controller] =='college_verification'  %>
                            <li><%= link_to "College", view_verifications_path, :class => "active" %></li>    
                        <%else%>
                            <li><%= link_to "College", view_verifications_path %></li>    
                        <%end%>
                    <%else%>
                        <% if params[:controller] =='student_verification'  %>
                            <li><%= link_to "Dashboard", apply_path, :class => "active" %></li>
                        <%else%>
                            <li><%= link_to "Dashboard", apply_path%></li>
                        <%end%> 
                    <%end%>

                <% end %>

                <% if params[:controller] =='landing_page' && params[:action] == 'index' %>
                    <!-- <li><a href="#about">About</a></li> -->
                    <li><a href="#contact">Contact Us</a></li>
                <%else%>
                    <li><%= link_to "Contact Us", "#{root_url}/#contact",method: :get %></li>
                <% end %>
                
                <li>
                    <a href="#" class="mn-has-sub"><i class="fa fa-search"></i> E-Verify</a>
                    <ul class="mn-sub">
                        <li>
                            <div class="mn-wrap">
                                <form id="verify-status" method="post" class="form">
                                    <div class="search-wrap">
                                        <button class="search-button animate" type="submit" title="Check">
                                            <i class="fa fa-search"></i>
                                        </button>
                                        <input type="text" id="everify" name="everify" class="form-control search-field" autocomplete="false" placeholder="Verification ID">
                                    </div>
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>

       
                <% if logged_in? %>
                        
                    <li>
                        <a href="#" class="mn-has-sub"><div class="icon-profile-male" style="margin-right:5px;"></div><%= current_user.name %> <i class="fa fa-angle-down"></i></a>                            
                        <!-- Sub -->
                        <ul class="mn-sub to-left">
                            
                            <% if is_college_admin?  %>
                                <li><%= link_to "Report Template", report_data_url %></li>
                            <%end%>
                            
                            <li><%= link_to "Profile", edit_user_path(current_user) %></li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to "Logout", logout_path, method: :delete %></li>   
                            
                        </ul>
                        <!-- End Sub -->                                
                    </li>

                    <!-- <li><%= link_to "Logout", logout_path, method: :delete %></li>  -->
                <% else %>
                    <% if params[:controller] != 'sessions' %>           
                        <li>
                            <%= link_to(login_path) do %>
                                <span style="font-size: 15px;" class="btn btn-mod btn-border round btn-small">Login</span>
                            <%end%>
                        </li>      
                    <% end %>
                <% end %>
            </ul>
        </div>
    </div>
</nav>
<div style="height: 75px; width: 100%;">&nbsp;</div>
<!-- End Navigation panel --> 


<div id="eVerifyModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="eVerifyModal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <p class="modal-title font-alt">Verification status</p>
            </div>
            <div class="modal-body black">
                <br>
                <p class="modal-title" id="ev_verify_status">Verification status</p><br>
                <div id="ev_success_content">
                    <p>Name: <span id="ev_name" style="font-weight: bold;"></span></p>
                    <p>Hallticket / Reg No: <span id="ev_hallticket_no" style="font-weight: bold;"></span></p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if !@disable_header_footer %>
    <title>Verify Online</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="utf-8">
    <meta name="author" content="Verify Online">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>  
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
    <!-- Favicons -->
    <link rel="shortcut icon" href=<%= image_path("favicon.png") %>>
    <link rel="apple-touch-icon" href=<%= image_path("apple-touch-icon.png") %>>
    <link rel="apple-touch-icon" sizes="72x72" href=<%= image_path("apple-touch-icon-72x72.png") %>>
    <link rel="apple-touch-icon" sizes="114x114" href=<%= image_path("apple-touch-icon-114x114.png") %>>
  <%end%>
</head>

<body class="appear-animate" style="height: auto; position: relative;">
  <%= render 'layouts/header' unless @disable_header_footer %>
  <%= yield %>
  <!-- <%= debug(params) if Rails.env.development? %> -->
  <%= render 'layouts/footer' unless @disable_header_footer  %>
</body>

</html>